### ISSUE TITLE
Build failed on Mac OS

### ISSUE THREAD

**Issue by jendas1** [ipython/ipywidgets#142]
Hi, 
I've tried to build this project (using pip3 install -e .) but I am getting this error.
```
FileError: '/components/bootstrap/less/variables.less' wasn't found. Tried - /components/bootstrap/less/variables.less,/Users/jendas/Google drive/Active projects/ipywidgets/ipywidgets/static/widgets/less/components/bootstrap/less/variables.less,/Users/jendas/Google drive/Active projects/ipywidgets/less_include/components/bootstrap/less/variables.less in /Users/jendas/Google drive/Active projects/ipywidgets/ipywidgets/static/widgets/less/widgets.less on line 2, column 1:
1 // minimal imports from bootstrap - only variables and mixins
2 @import "/components/bootstrap/less/variables.less";
3 @import "/components/bootstrap/less/mixins.less";
`lessc --include-path=./less_include ./ipywidgets/static/widgets/less/widgets.less ./ipywidgets/static/widgets/css/widgets.css` failed with status=1
```
I am not much into npm packager so I don't know how to fix it.

**Comment by minrk** [comment]
I suspect an earlier step is failing that isn't stopping progress. Try `python setup.py js css` first.

**Comment by jendas1** [comment]
The command you wrote is not recognized by setup.py so I tried python3 setup.py jsdeps to install only dependences. Here is the output (the same problem again):
```
> ipython-widget-deps@4.0.0 build /Users/jendas/Google drive/Active projects/ipywidgets
> npm run css && npm run buildtests


> ipython-widget-deps@4.0.0 precss /Users/jendas/Google drive/Active projects/ipywidgets
> rimraf ./ipywidgets/static/widgets/css/


> ipython-widget-deps@4.0.0 css /Users/jendas/Google drive/Active projects/ipywidgets
> node build_css.js

> lessc --include-path=./less_include ./ipywidgets/static/widgets/less/widgets.less ./ipywidgets/static/widgets/css/widgets.css
FileError: '/components/bootstrap/less/variables.less' wasn't found. Tried - /components/bootstrap/less/variables.less,/Users/jendas/Google drive/Active projects/ipywidgets/ipywidgets/static/widgets/less/components/bootstrap/less/variables.less,/Users/jendas/Google drive/Active projects/ipywidgets/less_include/components/bootstrap/less/variables.less in /Users/jendas/Google drive/Active projects/ipywidgets/ipywidgets/static/widgets/less/widgets.less on line 2, column 1:
1 // minimal imports from bootstrap - only variables and mixins
2 @import "/components/bootstrap/less/variables.less";
3 @import "/components/bootstrap/less/mixins.less";

`lessc --include-path=./less_include ./ipywidgets/static/widgets/less/widgets.less ./ipywidgets/static/widgets/css/widgets.css` failed with status=1

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "css"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE
npm ERR! ipython-widget-deps@4.0.0 css: `node build_css.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ipython-widget-deps@4.0.0 css script 'node build_css.js'.
npm ERR! This is most likely a problem with the ipython-widget-deps package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build_css.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ipython-widget-deps
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jendas/Google drive/Active projects/ipywidgets/npm-debug.log

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE
npm ERR! ipython-widget-deps@4.0.0 build: `npm run css && npm run buildtests`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ipython-widget-deps@4.0.0 build script 'npm run css && npm run buildtests'.
npm ERR! This is most likely a problem with the ipython-widget-deps package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run css && npm run buildtests
npm ERR! You can get their info via:
npm ERR!     npm owner ls ipython-widget-deps
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jendas/Google drive/Active projects/ipywidgets/npm-debug.log
Traceback (most recent call last):
  File "setup.py", line 294, in <module>
    setup(**setup_args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 210, in run
    check_call(['npm', 'run', 'build'])
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'run', 'build']' returned non-zero exit status 1
```

**Comment by minrk** [comment]
And what if you run `npm run bower` first?

**Comment by jendas1** [comment]
Thanks a lot, after I ran bower it worked. :)



Jan Studený
