### ISSUE TITLE
ImportError: No module named widgetsnbextension

### ISSUE THREAD

**Issue by fredthedead** [ipython/ipywidgets#568]
Getting the following error when trying to run the suggested command for loading ipywidgets

```
fredbox:~ fred$ jupyter nbextension enable --py widgetsnbextension
Traceback (most recent call last):
  File "/Users/fred/anaconda/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/Users/fred/anaconda/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/fred/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Users/fred/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 952, in start
    super(NBExtensionApp, self).start()
  File "/Users/fred/anaconda/lib/python2.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/Users/fred/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 860, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/Users/fred/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 836, in toggle_nbextension_python
    logger=self.log)
  File "/Users/fred/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 459, in enable_nbextension_python
    logger=logger)
  File "/Users/fred/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 374, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/Users/fred/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 1114, in _get_nbextension_metadata
    m = import_item(module)
  File "/Users/fred/anaconda/lib/python2.7/site-packages/traitlets/utils/importstring.py", line 41, in import_item
    return __import__(parts[0])
ImportError: No module named widgetsnbextension
fredbox:~ fred$ 
```

**Comment by jasongrout** [comment]
Did you install the most recent ipywidgets? That should have also installed the python package `widgetsnbextension`, which it seems you don't have installed.

**Comment by fredthedead** [comment]
I installed the latest available through conda. I tried running jupyter without the additional parameters ("nbextension enable") and it seems to have the extension's functionality... not sure what does it mean?

**Comment by jasongrout** [comment]
Does conda say widgetsnbextension is installed? What version of ipywidgets does it say is installed?

**Comment by fredthedead** [comment]
```
fredbox:fred$ conda list | grep widget
ipywidgets                4.1.1                    py27_0  
fredbox:fred$ 
```

**Comment by jasongrout** [comment]
It looks like you have an older version of ipywidgets that doesn't need the widgetsnbextension package. The widgetsnbextension package is needed in ipywidgets 5.0 or later. It also looks like conda does not yet have ipywidgets 5.x available.

What is your end goal here? If you just want to use widgets, the older version that you have installed and is available through conda should just work.

**Comment by fredthedead** [comment]
Yes, just wanted to have the full set of widgets available. So guess all good from my point of view.

**Comment by jasongrout** [comment]
So you're okay with closing this now, then?
