### ISSUE TITLE
Widget List.ipynb > Save notebook with snapshots > Freeze

### ISSUE THREAD

**Issue by gnestor** [ipython/ipywidgets#851]
Steps to reproduce:
1. Open [Widget List.ipynb](https://github.com/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20List.ipynb) in notebook (master)
2. Run all cells
3. Widgets > Save notebook with snapshots

Result: 

The save will get stuck at 86/87 and it will proceed to freeze the browser tab and the dashboard tab, requiring a server restart. There is no output in the browser console or server logs. This could very well be related to an error I see when running:

``` python
accordion = widgets.Accordion(children=[play, slider])
accordion.set_title(0, 'Play')
accordion.set_title(1, 'Slider')
accordion
```

```
accordion.children is not a function 
at http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js:43561:23 
at Function._.each._.forEach (http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js:1027:10) 
at AccordionView.update_titles (http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js:43557:12) 
at AccordionView.<anonymous> (http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js:43547:19) 
at triggerEvents (http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js:17507:58) 
at triggerApi (http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js:17495:20) 
at eventsApi (http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js:17293:15) 
at AccordionView.Events.trigger (http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js:17485:6) 
at WidgetManager._handle_display_view (http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js:380:11) 
at http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js:492:23
```

![image](https://cloud.githubusercontent.com/assets/512354/19653987/86a4569a-99cb-11e6-84a2-5ddc4b65487c.png)

**Comment by gnestor** [comment]
I'm getting a similar result but different error when trying to save snapshots of Widget Styling.ipynb:

```
Uncaught (in promise) TypeError: widgets.generateEmbedScript is not a function
    at http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js:616:40
```

**Comment by SylvainCorlay** [comment]
We just removed the ability to save png snapshots, so closing this issue.
